packages:
  - packages/*
catalogs:
  dev:
    '@antfu/eslint-config': ^4.11.0
    '@commitlint/cli': ^15.0.0
    bumpp: ^10.1.0
    consola: ^3.4.2
    eslint: ^9.24.0
    prettier: ^2.3.2
    eslint-plugin-format: ^1.0.1
    husky: ^8.0.2
    lint-staged: ^13.2.0
    typescript: ^5.8.3
    vite: ^6.2.5
    '@rollup/plugin-json': ^6.1.0
    '@rollup/plugin-replace': ^6.0.2
    rollup: ^4.39.0
    rollup-plugin-dts: ^6.2.1
    rollup-plugin-esbuild: ^6.2.1
    rollup-plugin-pure: ^0.3.0
    tinyglobby: ^0.2.12
  peer: 
    '@vueuse/core': ^9.10.0
    vue: ^3.5.13
    axios: ^0.21.1
    element-plus: 2.2.15
    qs: "^6.13.1"
  types:
    '@types/node': ^22.14.0